# crypto_data_processor.py
"""
`crypto_data_processor.py` - A CLI tool to update JSON files and MySQL database records in batches.

This module processes JSON files originally generated by `Crypto-DataLayer`. It performs the following actions:
1. Replaces the `elapsedTime` field with actual min and max `ts` values from the data.
2. Sets `extend.true_elapsedTime` to `true`.
3. Optionally sorts the `root.data` array based on `root.data[i].data[0].ts` (enabled by default).
   If sorted, sets `extend.sorted` to `true`.
4. Renames files from `<filePrefix>-[old_start]-[old_end].json` to `<filePrefix>-[new_start]-[new_end].json`.
5. Updates the MySQL database `elapsedStartTime` and `elapsedEndTime` fields in batches (optional).
"""

import os
import orjson # Changed from json to orjson
import re
import tempfile
import mysql.connector
from multiprocessing import Pool
from functools import partial
import argparse
import time
from tqdm import tqdm

import DataFile
import DataFile.data_name

# Compile the regex pattern for filename matching at the module level
FILENAME_PATTERN = re.compile(r'^(.*)-(\d+)-(\d+)\.json$')

def analyze_file(file_path, sort_data):
    """
    Analyze a JSON file, extract necessary information, optionally sort, and prepare for updating.
    Does not modify the original file or database.

    Args:
        file_path (str): Path to the JSON file.
        sort_data (bool): Whether to sort the root.data array by ts.

    Returns:
        tuple: (file_path, original_file_name, file_prefix, min_ts, max_ts, updated_data)
            or None if an error occurred.
    """
    original_file_name = os.path.basename(file_path)
    try:
        try: 
            dataName = DataFile.data_name.DataName(original_file_name)
        except Exception as e:
            tqdm.write(f"Parsing {file_path} error: {e}")
            return None
        file_prefix = dataName.prefix
        
        if dataName.category == 'LiquidationOrders':
            raise Exception(f"Not support `LiquidationOrders` now")

        with open(file_path, 'rb') as f: # Changed mode to 'rb' for orjson
            root = orjson.loads(f.read()) # Changed json.load to orjson.loads

        if 'data' not in root or not isinstance(root['data'], list) or not root['data']:
            # TODO: do some word here.
            tqdm.write(f"Warning: Skipping file with missing or empty 'data' list: {original_file_name}")
            return None

        if sort_data:
            # 使 Decorate-Sort-Undecorate 模式提高排序性能
            decorated = [(int(item['data'][0]['ts']), item) for item in root['data']]
            decorated.sort()
            root['data'] = [item for _, item in decorated]
            min_ts = root['data'][0]['data'][0]['ts']
            max_ts = root['data'][-1]['data'][0]['ts']
        else: 
            t = sorted(root['data'], key=lambda item: int(item['data'][0]['ts']))
            min_ts = t[0]['data'][0]['ts']
            max_ts = t[-1]['data'][0]['ts']

        root['elapsedTime'] = [min_ts, max_ts]
        root.setdefault('extend', {})['true_elapsedTime'] = True
        root['extend']['sorted'] = sort_data

        return (file_path, original_file_name, file_prefix, min_ts, max_ts, root)

    except orjson.JSONDecodeError as e: # Changed to orjson.JSONDecodeError
        tqdm.write(f"Error decoding JSON for {file_path}: {e}")
        return None
    except Exception as e:
        tqdm.write(f"Error analyzing {file_path}: {e}")
        return None

def process_file_batch_complete(file_batch, sort_data, db_params=None):
    """
    Process a batch of files completely within a single worker process:
    1. Read and analyze each file
    2. Update and rename each file
    3. Optionally update the database for the batch

    Args:
        file_batch (list): List of file paths to process.
        sort_data (bool): Whether to sort the root.data array by ts.
        db_params (dict, optional): Database connection parameters.
            If provided, database updates will be performed.

    Returns:
        tuple: (processed_count, db_updated_count)
            - processed_count: Number of files successfully processed
            - db_updated_count: Number of database records updated
    """
    processed_count = 0
    db_updates = []

    # Process each file in the batch
    for file_path in file_batch:
        result = analyze_file(file_path, sort_data)
        if not result:
            continue

        file_path, original_name, file_prefix, min_ts, max_ts, updated_data = result
        
        # Update and rename the file directly
        tmp_file_path = None
        try:
            temp_dir = os.path.dirname(file_path)
            with tempfile.NamedTemporaryFile(mode='wb', dir=temp_dir, delete=False, suffix='.tmpjson') as tmp_file:
                tmp_file.write(orjson.dumps(updated_data))
                tmp_file_path = tmp_file.name

            new_file_name = f"{file_prefix}-{min_ts}-{max_ts}.json"
            new_file_path = os.path.join(temp_dir, new_file_name)
            os.replace(tmp_file_path, new_file_path)
            if file_path != new_file_path and os.path.exists(file_path):
                try:
                    if not os.path.samefile(file_path, new_file_path):
                        os.remove(file_path)
                except OSError as e:
                    tqdm.write(f"Warning: Could not remove original file {file_path}: {e}")
            
            processed_count += 1
            
            # Add to database updates if database parameters are provided
            if db_params:
                db_updates.append((original_name, min_ts, max_ts))
                
        except Exception as e:
            tqdm.write(f"Error updating file {file_path}: {e}")
            if tmp_file_path and os.path.exists(tmp_file_path):
                try:
                    os.remove(tmp_file_path)
                except OSError as e:
                    tqdm.write(f"Warning: Could not remove temporary file {tmp_file_path}: {e}")

    # Update database if needed
    db_updated_count = 0
    if db_params and db_updates:
        try:
            conn = None
            cursor = None
            try:
                conn = mysql.connector.connect(
                    host=db_params['host'],
                    user=db_params['user'],
                    password=db_params['password'],
                    database=db_params['database'],
                    autocommit=False
                )
                cursor = conn.cursor()
                query = f"UPDATE `{db_params['table']}` SET `elapsedStartTime` = %s, `elapsedEndTime` = %s WHERE `fileBaseName` = %s"
                update_data = [(min_ts, max_ts, original_name) for original_name, min_ts, max_ts in db_updates]
                cursor.executemany(query, update_data)
                conn.commit()
                db_updated_count = cursor.rowcount
                
            except mysql.connector.Error as e:
                if conn:
                    conn.rollback()
                tqdm.write(f"Database batch update error in worker: {e}")
                
            finally:
                if cursor:
                    cursor.close()
                if conn and conn.is_connected():
                    conn.close()
        except Exception as e:
            tqdm.write(f"Error during database update in worker: {e}")

    return processed_count, db_updated_count

def update_database_batch(updates, db_host, db_user, db_password, db_name, table_name):
    """
    Update the MySQL database with new elapsed times for multiple files in a single transaction.

    Args:
        updates (list): List of tuples (original_file_name, min_ts, max_ts).
        db_host (str): Database host.
        db_user (str): Database username.
        db_password (str): Database password.
        db_name (str): Database name.
        table_name (str): Database table name.

    Returns:
        bool: True if the update was successful, False otherwise.
    """
    if not updates:
        return True

    conn = None
    cursor = None
    try:
        conn = mysql.connector.connect(
            host=db_host,
            user=db_user,
            password=db_password,
            database=db_name,
            autocommit=False
        )
        cursor = conn.cursor()
        query = f"UPDATE `{table_name}` SET `elapsedStartTime` = %s, `elapsedEndTime` = %s WHERE `fileBaseName` = %s"
        update_data = [(min_ts, max_ts, original_name) for original_name, min_ts, max_ts in updates]
        cursor.executemany(query, update_data)
        conn.commit()
        tqdm.write(f"Successfully updated {cursor.rowcount} database records.")
        return True

    except mysql.connector.Error as e:
        if conn:
            conn.rollback()
            tqdm.write("Database transaction rolled back due to error.")
        tqdm.write(f"Database batch update error: {e}")
        return False

    finally:
        if cursor:
            cursor.close()
        if conn and conn.is_connected():
            conn.close()

def update_files(file_updates):
    """Update and rename files based on processed data."""
    for file_path, original_name, file_prefix, min_ts, max_ts, updated_data in file_updates:
        tmp_file_path = None
        try:
            temp_dir = os.path.dirname(file_path)
            # Changed mode to 'wb' and removed encoding for orjson.dumps which returns bytes
            with tempfile.NamedTemporaryFile(mode='wb', dir=temp_dir, delete=False, suffix='.tmpjson') as tmp_file:
                tmp_file.write(orjson.dumps(updated_data)) # Changed json.dump to tmp_file.write(orjson.dumps(...))
                tmp_file_path = tmp_file.name

            new_file_name = f"{file_prefix}-{min_ts}-{max_ts}.json"
            new_file_path = os.path.join(temp_dir, new_file_name)
            os.replace(tmp_file_path, new_file_path)
            if file_path != new_file_path and os.path.exists(file_path):
                try:
                    if not os.path.samefile(file_path, new_file_path):
                        os.remove(file_path)
                except OSError as e:
                    tqdm.write(f"Warning: Could not remove original file {file_path}: {e}")

        except Exception as e:
            tqdm.write(f"Error updating file {file_path}: {e}")
            if tmp_file_path and os.path.exists(tmp_file_path):
                try:
                    os.remove(tmp_file_path)
                except OSError as e:
                    tqdm.write(f"Warning: Could not remove temporary file {tmp_file_path}: {e}")

def find_json_files(directory):
    """Recursively find all JSON files matching the expected naming pattern."""
    json_files = []
    pattern = re.compile(r'^.*-\d+-\d+\.json$')
    for root, _, files in os.walk(directory):
        for file in files:
            if pattern.match(file) and os.path.isfile(os.path.join(root, file)):
                json_files.append(os.path.join(root, file))
    return json_files

def main():
    """Main function to process files in batches with a progress bar."""
    start_time = time.time()

    parser = argparse.ArgumentParser(
        description="Update JSON files and optionally update database records in batches.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--files', nargs='+', help="List of specific JSON files to process.")
    group.add_argument('--dir', help="Directory containing JSON files to process recursively.")
    parser.add_argument('--no-sort', dest='sort_data', action='store_false', default=True,
                        help="Disable sorting of the root.data array by timestamp.")
    parser.add_argument('--db-host', default='localhost', help="MySQL database host.")
    parser.add_argument('--db-user', help="MySQL database username.")
    parser.add_argument('--db-password', help="MySQL database password.")
    parser.add_argument('--db-name', help="MySQL database name.")
    parser.add_argument('--table-name', default='processedfiles', help="MySQL table name.")
    parser.add_argument('--batch-size', type=int, default=100, help="Number of files per processing batch.")
    parser.add_argument('--worker-processes', type=int, default=os.cpu_count(),
                        help="Number of worker processes.")

    args = parser.parse_args()
    update_db = bool(args.db_user and args.db_password and args.db_name)

    if args.dir:
        tqdm.write(f"Searching for files recursively in directory: {args.dir}")
        file_paths = find_json_files(args.dir)
    else:
        file_paths = [f for f in (args.files or []) if os.path.isfile(f)]
        if not file_paths:
            tqdm.write("No valid JSON files found or specified to process.")
            return

    tqdm.write(f"Found {len(file_paths)} files to process.")

    # 按 batch_size 划分文件列表
    file_batches = [file_paths[i:i + args.batch_size] for i in range(0, len(file_paths), args.batch_size)]
    num_workers = min(args.worker_processes, len(file_batches)) or 1

    # Prepare database parameters if database updates are enabled
    db_params = None
    if update_db:
        db_params = {
            'host': args.db_host,
            'user': args.db_user,
            'password': args.db_password,
            'database': args.db_name,
            'table': args.table_name
        }

    # Create a partial function with sort_data and db_params
    process_batch_partial = partial(process_file_batch_complete, sort_data=args.sort_data, db_params=db_params)

    tqdm.write(f"Starting processing with {num_workers} worker process(es)...")

    total_processed = 0
    total_db_updated = 0
    pool = None
    try:
        if num_workers > 1:
            pool = Pool(processes=num_workers)
            results = pool.imap_unordered(process_batch_partial, file_batches)
            for processed_count, db_updated_count in tqdm(results, total=len(file_batches), desc="Processing batches"):
                total_processed += processed_count
                total_db_updated += db_updated_count
            pool.close()
            pool.join()
        else:
            for batch in tqdm(file_batches, desc="Processing batches"):
                processed_count, db_updated_count = process_batch_partial(batch)
                total_processed += processed_count
                total_db_updated += db_updated_count

        tqdm.write(f"Processing finished. Processed {total_processed} files, updated {total_db_updated} database records.")

    except Exception as e:
        tqdm.write(f"Error during processing: {e}")
        raise
    finally:
        if pool:
            pool.terminate()

    end_time = time.time()
    total_time = end_time - start_time
    avg_time_per_file = total_time / total_processed if total_processed else 0
    tqdm.write("\n--- Processing Summary ---")
    tqdm.write(f"  Total files processed: {total_processed}")
    tqdm.write(f"  Total database records updated: {total_db_updated}")
    tqdm.write(f"  Total processing time: {total_time:.2f} seconds")
    tqdm.write(f"  Average time per file: {avg_time_per_file:.4f} seconds")

if __name__ == '__main__':
    main()
