/**
 * crypto_data_processor.cpp - A CLI tool to update JSON files and MySQL database records in batches.
 *
 * This program processes JSON files originally generated by Crypto-DataLayer. It performs:
 * 1. Replaces the elapsedTime field with actual min and max ts values from the data
 * 2. Sets extend.true_elapsedTime to true
 * 3. Optionally sorts the root.data array based on timestamp (enabled by default)
 * 4. Renames files from <filePrefix>-[old_start]-[old_end].json to <filePrefix>-[new_start]-[new_end].json
 * 5. Updates MySQL database elapsedStartTime and elapsedEndTime fields in batches (optional)
 */

#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <regex>
#include <filesystem>
#include <algorithm>
#include <thread>
#include <mutex>
#include <chrono>
#include <functional>
#include <limits>
#include <optional>
#include <cstdio>
#include <random>
#include <atomic>
#include <glaze/glaze.hpp>
// #include <mysqlx/xdevapi.h>
#include <argparse/argparse.hpp>
#include <iomanip>
#include <sstream>

namespace fs = std::filesystem;

// Regular expression for filename matching, compiled once
const std::regex FILENAME_PATTERN("^(.*?)-(\\d+)-(\\d+)\\.json$");

// Mutex for thread-safe console output
std::mutex console_mutex;

// Thread-safe logger class
class FileLogger {
private:
    std::mutex log_mutex;
    std::string log_file_path;

public:
    FileLogger(const std::string& path) : log_file_path(path) {
        // Create or clear the log file
        std::ofstream log_file(log_file_path, std::ios::out | std::ios::trunc);
        if (log_file.is_open()) {
            log_file << "Timestamp,Filename,ProcessingTimeMs,StartTimestamp,EndTimestamp" << std::endl;
            log_file.close();
        }
    }

    void log_file_processing(const std::string& filename, long long processing_time_ms, 
                           const std::chrono::system_clock::time_point& start_time,
                           const std::chrono::system_clock::time_point& end_time) {
        std::lock_guard<std::mutex> lock(log_mutex);
        
        // Get current time for timestamp
        auto now = std::chrono::system_clock::now();
        auto now_time_t = std::chrono::system_clock::to_time_t(now);
        std::stringstream timestamp;
        timestamp << std::put_time(std::localtime(&now_time_t), "%Y-%m-%d %H:%M:%S");
        
        // Open file in append mode
        std::ofstream log_file(log_file_path, std::ios::app);
        if (log_file.is_open()) {
            // Convert start/end times to timestamps
            auto start_time_t = std::chrono::system_clock::to_time_t(start_time);
            auto end_time_t = std::chrono::system_clock::to_time_t(end_time);
            
            std::stringstream start_timestamp, end_timestamp;
            start_timestamp << std::put_time(std::localtime(&start_time_t), "%Y-%m-%d %H:%M:%S");
            end_timestamp << std::put_time(std::localtime(&end_time_t), "%Y-%m-%d %H:%M:%S");
            
            log_file << timestamp.str() << "," 
                     << filename << "," 
                     << processing_time_ms << ","
                     << start_timestamp.str() << ","
                     << end_timestamp.str() << std::endl;
            log_file.close();
        }
    }
};

// Global shared logger
std::shared_ptr<FileLogger> g_logger;

// Global progress tracking
std::atomic<int> files_processed{0};
std::atomic<int> db_records_updated{0};
int total_files = 0;

// Thread-safe console output
template<typename... Args>
void safe_print(const char* format, Args... args) {
    std::lock_guard<std::mutex> lock(console_mutex);
    printf(format, args...);
    fflush(stdout);
}

// Update progress bar
void update_progress() {
    int processed = files_processed.load();
    if (total_files > 0) {
        int percent = static_cast<int>(100.0 * processed / total_files);
        std::lock_guard<std::mutex> lock(console_mutex);
        printf("\rProgress: [");
        int pos = 50 * processed / total_files;
        for (int i = 0; i < 50; ++i) {
            if (i < pos) printf("=");
            else if (i == pos) printf(">");
            else printf(" ");
        }
        printf("] %d%% (%d/%d)", percent, processed, total_files);
        fflush(stdout);
    }
}

using BookLevel = std::array<std::string, 4>;

struct DataItem {
    std::vector<BookLevel> asks;
    std::vector<BookLevel> bids;
    std::string ts;
    int64_t checksum;
    int64_t prevSeqId;
    int64_t seqId;
};

struct Arg {
    std::string channel;
    std::optional<std::string> instId;
    std::optional<std::string> instType;
    std::optional<std::string> InstFamily;
    std::optional<std::string> uly;
};

struct BookData {
    Arg arg;
    std::array<DataItem, 1> data;
    std::string action;
};

struct Extend {
    bool sorted;
    bool true_elapsedTime;
};

struct JsonData {
    std::array<int64_t, 2> elapsedTime;
    std::vector<BookData> data;
    std::optional<Extend> extend;
};

// Database connection parameters
struct DbParams {
    std::string host;
    std::string user;
    std::string password;
    std::string database;
    std::string table;
    int port = 33060;
};

// Result of file analysis
struct FileAnalysisResult {
    std::string file_path;
    std::string original_file_name;
    std::string file_prefix;
    int64_t min_ts;
    int64_t max_ts;
    JsonData updated_data;
};

// Generate a temporary file name
std::string generate_temp_filename(const std::string& dir) {
    static std::random_device rd;
    static std::mt19937 gen(rd());
    static std::uniform_int_distribution<> dis(0, 999999);
    
    return (fs::path(dir) / fs::path(std::to_string(dis(gen)) + ".tmpjson")).string();
}

// Analyze a JSON file
std::optional<FileAnalysisResult> analyze_file(const std::string& file_path, bool sort_data) {
    try {
        std::string original_file_name = fs::path(file_path).filename().string();
        std::smatch match;
        
        if (!std::regex_match(original_file_name, match, FILENAME_PATTERN)) {
            safe_print("Warning: Skipping file with invalid name format: %s\n", original_file_name.c_str());
            return std::nullopt;
        }
        
        std::string file_prefix = match[1].str();
                
        // Parse JSON
        JsonData root;
        auto ec = glz::read_file_json(root, file_path, std::string{});
        if (ec) {
            safe_print("Error reading JSON: %d - %s\n", static_cast<int>(ec.ec), glz::format_error(ec).c_str());
            return std::nullopt;
        }
        
        if (root.data.empty()) {
            safe_print("Warning: Skipping file with missing or empty 'data' list: %s\n", 
                original_file_name.c_str());
            return std::nullopt;
        }
        
        // Extract and validate timestamps
        std::vector<int64_t> ts_list_int;
        std::vector<BookData> valid_data_items;
        
        for (size_t i = 0; i < root.data.size(); ++i) {
            try {
                const auto& entry = root.data[i];
                if (!entry.data.empty() && !entry.data[0].ts.empty()) {
                    const auto& ts_str = entry.data[0].ts;
                    
                    // Check if string contains only digits
                    bool is_digit = !ts_str.empty() && 
                                    std::all_of(ts_str.begin(), ts_str.end(), ::isdigit);
                    
                    if (is_digit) {
                        int64_t ts_int = std::stoll(ts_str);
                        ts_list_int.push_back(ts_int);
                        valid_data_items.push_back(entry);
                    } else {
                        safe_print("Warning: Invalid 'ts' format in item %zu within %s\n", 
                            i, original_file_name.c_str());
                    }
                } else {
                    safe_print("Warning: Invalid structure in item %zu within %s\n", 
                        i, original_file_name.c_str());
                }
            } catch (const std::exception& e) {
                safe_print("Warning: Error in item %zu within %s: %s\n", 
                    i, original_file_name.c_str(), e.what());
            }
        }
        
        if (ts_list_int.empty()) {
            safe_print("Warning: No valid 'ts' values found in %s\n", original_file_name.c_str());
            return std::nullopt;
        }
        
        // Find min and max timestamps
        int64_t min_ts = *std::min_element(ts_list_int.begin(), ts_list_int.end());
        int64_t max_ts = *std::max_element(ts_list_int.begin(), ts_list_int.end());
        
        // Sort data if requested
        if (sort_data && !root.data.empty()) {
            std::sort(root.data.begin(), root.data.end(), 
                [](const BookData& a, const BookData& b) {
                    if (a.data.empty() || b.data.empty()) return false;
                    return std::stoll(a.data[0].ts) < std::stoll(b.data[0].ts);
                });
        }
        
        // Update elapsedTime and extend fields
        root.elapsedTime = {min_ts, max_ts};
        if (!root.extend) {
            root.extend = Extend{}; // Initialize if not present
        }
        root.extend->true_elapsedTime = true; // Use -> to access members
        root.extend->sorted = sort_data && !root.data.empty();
        
        FileAnalysisResult result;
        result.file_path = file_path;
        result.original_file_name = original_file_name;
        result.file_prefix = file_prefix;
        result.min_ts = min_ts;
        result.max_ts = max_ts;
        result.updated_data = std::move(root);
        
        return result;
        
    } catch (const std::exception& e) {
        safe_print("Error analyzing %s: %s\n", file_path.c_str(), e.what());
        return std::nullopt;
    }
}

// Update a file with new content and rename it
bool update_file(const FileAnalysisResult& result) {
    try {
        std::string temp_dir = fs::path(result.file_path).parent_path().string();
        std::string tmp_file_path = generate_temp_filename(temp_dir);
        
        // Write to temporary file
        {
            std::string json_str;
            auto write_result = glz::write_json(result.updated_data, json_str);
            if (write_result.ec != glz::error_code::none) {
                safe_print("Error serializing JSON for %s: Error code %d\n", 
                    result.file_path.c_str(), static_cast<int>(write_result.ec));
                return false;
            }
            
            std::ofstream tmp_file(tmp_file_path, std::ios::binary);
            if (!tmp_file.is_open()) {
                safe_print("Error creating temporary file %s\n", tmp_file_path.c_str());
                return false;
            }
            
            tmp_file.write(json_str.c_str(), json_str.length());
            tmp_file.close();
        }
        
        // Create new filename
        std::string new_file_name = result.file_prefix + "-" + 
                                std::to_string(result.min_ts) + "-" + 
                                std::to_string(result.max_ts) + ".json";
        std::string new_file_path = (fs::path(temp_dir) / fs::path(new_file_name)).string();
        
        // Rename temporary file to new file
        try {
            fs::rename(tmp_file_path, new_file_path);
            
            // Remove original file if different from new file
            if (result.file_path != new_file_path && fs::exists(result.file_path)) {
                if (!fs::equivalent(result.file_path, new_file_path)) {
                    fs::remove(result.file_path);
                }
            }
            
            
            return true;
            
        } catch (const fs::filesystem_error& e) {
            safe_print("Error renaming file %s to %s: %s\n", 
                tmp_file_path.c_str(), new_file_path.c_str(), e.what());
            
            // Clean up temporary file on error
            if (fs::exists(tmp_file_path)) {
                try {
                    fs::remove(tmp_file_path);
                } catch (...) {
                    safe_print("Warning: Could not remove temporary file %s\n", tmp_file_path.c_str());
                }
            }
            
            return false;
        }
        
    } catch (const std::exception& e) {
        safe_print("Error updating file %s: %s\n", result.file_path.c_str(), e.what());
        return false;
    }
}

// Update database records in batch
// bool update_database_batch(const std::vector<FileAnalysisResult>& results, const DbParams& db_params) {
//     if (results.empty()) {
//         return true;
//     }
    
//     try {
//         // Create session
//         mysqlx::Session session(
//             mysqlx::SessionOption::HOST, db_params.host,
//             mysqlx::SessionOption::PORT, db_params.port,
//             mysqlx::SessionOption::USER, db_params.user,
//             mysqlx::SessionOption::PWD, db_params.password,
//             mysqlx::SessionOption::DB, db_params.database
//         );
        
//         // Start transaction
//         session.startTransaction();
        
//         // Prepare statement
//         mysqlx::Table table = session.getSchema(db_params.database).getTable(db_params.table);
        
//         int updated_count = 0;
        
//         for (const auto& result : results) {
//             try {
//                 table.update()
//                     .set("elapsedStartTime", result.min_ts)
//                     .set("elapsedEndTime", result.max_ts)
//                     .where("fileBaseName = :name")
//                     .bind("name", result.original_file_name)
//                     .execute();
                
//                 updated_count++;
//             } catch (const mysqlx::Error& e) {
//                 safe_print("Error updating database record for %s: %s\n", 
//                     result.original_file_name.c_str(), e.what());
//             }
//         }
        
//         // Commit transaction
//         session.commit();
        
//         db_records_updated += updated_count;
//         safe_print("Successfully updated %d database records.\n", updated_count);
        
//         return true;
        
//     } catch (const mysqlx::Error& e) {
//         safe_print("Database batch update error: %s\n", e.what());
//         return false;
//     } catch (const std::exception& e) {
//         safe_print("Error during database update: %s\n", e.what());
//         return false;
//     }
// }

// Process a batch of files completely
void process_file_batch_complete(const std::vector<std::string>& file_batch, 
                                bool sort_data, 
                                const std::optional<DbParams>& db_params) {
    std::vector<FileAnalysisResult> successful_results;
    
    // Process each file in the batch
    for (const auto& file_path : file_batch) {
        // Start timing for this file
        auto file_start_time = std::chrono::high_resolution_clock::now();
        
        auto result = analyze_file(file_path, sort_data);
        if (!result) {
            safe_print("skip %s ...\n", file_path.c_str());
            continue;
        }
        
        bool update_success = update_file(*result);
        
        // End timing for this file
        auto file_end_time = std::chrono::high_resolution_clock::now();
        auto file_processing_time = std::chrono::duration_cast<std::chrono::milliseconds>(
            file_end_time - file_start_time);
        
        if (update_success) {
            // Log the processing time
            if (g_logger) {
                std::string filename = fs::path(file_path).filename().string();
                g_logger->log_file_processing(filename, file_processing_time.count(), 
                                           file_start_time, file_end_time);
            }
            
            files_processed++;
            
            // Update progress periodically
            if (files_processed % 100 == 0) {
                update_progress();
            }
        }
    }
    
    // Update database if needed and there are successful results
    if (db_params && !successful_results.empty()) {
        // update_database_batch(successful_results, *db_params);
    }
}

// Find all JSON files matching the expected naming pattern
std::vector<std::string> find_json_files(const std::string& directory) {
    std::vector<std::string> json_files;
    
    try {
        for (const auto& entry : fs::recursive_directory_iterator(directory)) {
            if (entry.is_regular_file()) {
                std::string filename = entry.path().filename().string();
                if (std::regex_match(filename, FILENAME_PATTERN)) {
                    json_files.push_back(entry.path().string());
                }
            }
        }
    } catch (const fs::filesystem_error& e) {
        safe_print("Error searching directory %s: %s\n", directory.c_str(), e.what());
    }
    
    return json_files;
}

// Main function
int main(int argc, char* argv[]) {
    auto start_time = std::chrono::high_resolution_clock::now();
    
    // Setup argument parser
    argparse::ArgumentParser program("crypto_data_processor");
    program.add_description("Update JSON files and optionally update database records in batches.");
    
    // Create mutually exclusive group for input source
    program.add_argument("--files")
        .help("List of specific JSON files to process")
        .nargs(argparse::nargs_pattern::at_least_one)
        .metavar("FILE");
        
    program.add_argument("--dir")
        .help("Directory containing JSON files to process recursively")
        .metavar("DIRECTORY");
    
    program.add_argument("--no-sort")
        .help("Disable sorting of the root.data array by timestamp")
        .default_value(false)
        .implicit_value(true)
        .nargs(0);
    
    program.add_argument("--db-host")
        .help("MySQL database host")
        .default_value(std::string("localhost"))
        .metavar("HOST");
    
    program.add_argument("--db-user")
        .help("MySQL database username")
        .metavar("USER");
    
    program.add_argument("--db-password")
        .help("MySQL database password")
        .metavar("PASSWORD");
    
    program.add_argument("--db-name")
        .help("MySQL database name")
        .metavar("DATABASE");
    
    program.add_argument("--table-name")
        .help("MySQL table name")
        .default_value(std::string("processedfiles"))
        .metavar("TABLE");
    
    program.add_argument("--batch-size")
        .help("Number of files per processing batch")
        .default_value(100)
        .scan<'i', int>()
        .metavar("SIZE");
    
    program.add_argument("--worker-threads")
        .help("Number of worker threads")
        .default_value(static_cast<int>(std::thread::hardware_concurrency()))
        .scan<'i', int>()
        .metavar("THREADS");
        
    program.add_argument("--log-file")
        .help("Path to the processing time log file")
        .default_value(std::string("file_processing_times.csv"))
        .metavar("LOG_FILE");
    
    // Parse arguments
    try {
        program.parse_args(argc, argv);
    } catch (const std::exception& e) {
        std::cerr << e.what() << std::endl;
        std::cerr << program;
        return 1;
    }
    
    // Check if either --files or --dir is provided
    if (!program.is_used("--files") && !program.is_used("--dir")) {
        std::cerr << "Error: Either --files or --dir must be provided." << std::endl;
        std::cerr << program;
        return 1;
    }
    
    // Get file paths
    std::vector<std::string> file_paths;
    
    if (program.is_used("--dir")) {
        std::string dir = program.get<std::string>("--dir");
        std::cout << "Searching for files recursively in directory: " << dir << std::endl;
        file_paths = find_json_files(dir);
    } else {
        auto files = program.get<std::vector<std::string>>("--files");
        for (const auto& file : files) {
            if (fs::is_regular_file(file)) {
                file_paths.push_back(file);
            }
        }
    }
    
    if (file_paths.empty()) {
        std::cout << "No valid JSON files found or specified to process." << std::endl;
        return 0;
    }
    
    // Shuffle files to distribute large files evenly
    std::random_device rd;
    std::mt19937 g(rd());
    std::shuffle(file_paths.begin(), file_paths.end(), g);
    
    std::cout << "Found " << file_paths.size() << " files to process (randomly shuffled)." << std::endl;
    total_files = file_paths.size();
    
    // Prepare settings
    bool sort_data = !program.get<bool>("--no-sort");
    int batch_size = program.get<int>("--batch-size");
    int num_threads = program.get<int>("--worker-threads");
    
    // Initialize the logger
    std::string log_file_path = program.get<std::string>("--log-file");
    g_logger = std::make_shared<FileLogger>(log_file_path);
    std::cout << "Processing times will be logged to: " << log_file_path << std::endl;
    
    // Check database parameters
    std::optional<DbParams> db_params;
    if (program.is_used("--db-user") && program.is_used("--db-password") && program.is_used("--db-name")) {
        db_params = DbParams{
            .host = program.get<std::string>("--db-host"),
            .user = program.get<std::string>("--db-user"),
            .password = program.get<std::string>("--db-password"),
            .database = program.get<std::string>("--db-name"),
            .table = program.get<std::string>("--table-name")
        };
        std::cout << "Database updates enabled." << std::endl;
    } else {
        std::cout << "Database updates disabled (missing parameters)." << std::endl;
    }
    
    // Divide files into batches
    std::vector<std::vector<std::string>> file_batches;
    for (size_t i = 0; i < file_paths.size(); i += batch_size) {
        std::vector<std::string> batch;
        for (size_t j = i; j < i + batch_size && j < file_paths.size(); ++j) {
            batch.push_back(file_paths[j]);
        }
        file_batches.push_back(std::move(batch));
    }
    
    // Adjust number of threads if necessary
    num_threads = std::min(num_threads, static_cast<int>(file_batches.size()));
    num_threads = std::max(1, num_threads);
    
    std::cout << "Starting processing with " << num_threads << " worker thread(s)..." << std::endl;
    
    // Process batches using multiple threads
    std::vector<std::thread> threads;
    
    if (num_threads > 1) {
        // Distribute batches among threads
        for (int t = 0; t < num_threads; ++t) {
            // Note: g_logger is a global variable, so it's accessible in the thread
            threads.emplace_back([t, num_threads, &file_batches, sort_data, &db_params]() {
                for (size_t i = t; i < file_batches.size(); i += num_threads) {
                    process_file_batch_complete(file_batches[i], sort_data, db_params);
                }
            });
        }
        
        // Wait for all threads to complete
        for (auto& thread : threads) {
            thread.join();
        }
    } else {
        // Single-threaded processing
        for (const auto& batch : file_batches) {
            process_file_batch_complete(batch, sort_data, db_params);
        }
    }
    
    // Final progress update
    update_progress();
    std::cout << std::endl;
    
    // Calculate elapsed time
    auto end_time = std::chrono::high_resolution_clock::now();
    auto duration = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time);
    double total_seconds = duration.count() / 1000.0;
    double avg_time_per_file = total_seconds / files_processed.load();
    
    // Print summary
    std::cout << "\n--- Processing Summary ---" << std::endl;
    std::cout << "  Total files processed: " << files_processed << std::endl;
    std::cout << "  Total database records updated: " << db_records_updated << std::endl;
    std::cout << "  Total processing time: " << std::fixed << std::setprecision(2) << total_seconds << " seconds" << std::endl;
    std::cout << "  Average time per file: " << std::fixed << std::setprecision(4) << avg_time_per_file << " seconds" << std::endl;
    
    return 0;
}
